/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoanSystems;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Loan_Systems extends javax.swing.JFrame {

    /**
     * Creates new form Loan_Systems
     */
    public Loan_Systems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Reset = new javax.swing.JButton();
        GenerateReceipt = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        LoanCal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtEnter = new javax.swing.JTextField();
        jtxtnumberofyears = new javax.swing.JTextField();
        jtxtEnterloanamount = new javax.swing.JTextField();
        jlblmonthlyPayment = new javax.swing.JTextField();
        jlbltotalPayment = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Management Systems");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setPreferredSize(new java.awt.Dimension(1250, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset.setText("Reset Calculator");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 160, 40));

        GenerateReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GenerateReceipt.setText("Generate Receipt");
        GenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReceiptActionPerformed(evt);
            }
        });
        jPanel3.add(GenerateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 160, 40));

        jExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jExit.setText("Exit Calculator");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jPanel3.add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 150, 40));

        LoanCal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoanCal.setText("Calculate Loan");
        LoanCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanCalActionPerformed(evt);
            }
        });
        jPanel3.add(LoanCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1250, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Loan Management System Calculator");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 930, 44));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1250, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter number of years as an integer e.g 4");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter annual monthly interest e.g 3.5");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Enter the amount of Loan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Monthly payment");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Total payment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));
        getContentPane().add(jtxtEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 210, 30));

        jtxtnumberofyears.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnumberofyearsKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtnumberofyears, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 210, 30));
        getContentPane().add(jtxtEnterloanamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 210, 30));
        getContentPane().add(jlblmonthlyPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 210, 30));
        getContentPane().add(jlbltotalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 210, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 320, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
       frame=new JFrame("Exit");
				if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Loan Management Systems",
						JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION) {
					System.exit(0);}
    }//GEN-LAST:event_jExitActionPerformed

    private void GenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReceiptActionPerformed
        String annualInterestRate= String.format(jtxtEnter.getText());
		String numberOfYears= String.format(jtxtnumberofyears.getText());
		String loanAmount=String.format(jtxtEnterloanamount.getText());
		
		String monthlyPayment=String.format(jlblmonthlyPayment.getText());
		String totalPayment= String.format(jlbltotalPayment.getText());
		//=======================================================================
		
		int refs=1325 +(int) (Math.random()*4238);
		//=======================================================================
		  Calendar timer= Calendar.getInstance();
		  timer.getTime();
		  SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
		  tTime.format(timer.getTime());
		  SimpleDateFormat TDate=new SimpleDateFormat("dd-MMM-yyyy");
		  TDate.format(timer.getTime());
		//=======================================================================
		
		  
		  jtxtReceipt.append("\tLOAN MANAGEMENT SYSTEM\n-------------------------------------------------------------------------------------------\n"+
		 "Reference:\t\t\t" +refs+
		 "\n=======================================================\t"+
		 "\nInterest rate:\t\t\t" + annualInterestRate +
		 "\nRepayment years:\t\t" + numberOfYears+
		 "\nAmount of Loan:\t\t"  +"$"+ loanAmount +
		 "\nMonthly payment:\t\t" + monthlyPayment +
		 "\nTotal payment:\t\t\t " + totalPayment +
		 
		 "\n=======================================================\t"+
		 "\nDate:" +TDate.format(timer.getTime()) +
		 "\t\tTime :" + tTime.format(timer.getTime())+
		 "\n\n\t\t Thank You \n" );
		 
		
    }//GEN-LAST:event_GenerateReceiptActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jtxtEnter.setText(null);
				jtxtnumberofyears.setText(null);
				jtxtEnterloanamount.setText(null);
				jlblmonthlyPayment.setText(null);
				jlbltotalPayment.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void LoanCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanCalActionPerformed
        
        //==================================================================================
        double annualInterestRate=Double.parseDouble(jtxtEnter.getText());
        double monthlyInterestRate=annualInterestRate/1200;
        
        int numberOfYears=Integer.parseInt(jtxtnumberofyears.getText());
       Double loanAmount=Double.parseDouble(jtxtEnterloanamount.getText());
       
       //====================================================================================
       
       double monthlyPayment =loanAmount* monthlyInterestRate/(1-1/Math.pow(1+monthlyInterestRate,numberOfYears*12));
       String imonthlyPayment;
       imonthlyPayment= Double.toString(monthlyPayment);
       imonthlyPayment = String.format("$%.2f",monthlyPayment);
       jlblmonthlyPayment.setText(imonthlyPayment);
       
       //===================================================================================
       
        double totalPayment =monthlyPayment*numberOfYears*12;
       String itotalPayment;
       
       itotalPayment = String.format("$%.2f",totalPayment);
       jlbltotalPayment.setText(itotalPayment);
       
    }//GEN-LAST:event_LoanCalActionPerformed

    private void jtxtnumberofyearsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnumberofyearsKeyTyped
       char iNumber=evt.getKeyChar();
       if(!(Character.isDigit(iNumber))
               ||(iNumber==KeyEvent.VK_BACK_SPACE)
               ||(iNumber==KeyEvent.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtnumberofyearsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan_Systems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReceipt;
    private javax.swing.JButton LoanCal;
    private javax.swing.JButton Reset;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jlblmonthlyPayment;
    private javax.swing.JTextField jlbltotalPayment;
    private javax.swing.JTextField jtxtEnter;
    private javax.swing.JTextField jtxtEnterloanamount;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtnumberofyears;
    // End of variables declaration//GEN-END:variables
}
